language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update
  - sudo xargs -a apt-packages.txt apt-get install --fix-missing
install:
  - sudo apt-get install python-matplotlib python-numpy python-scipy python-sklearn
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - sudo mv ease/data/nltk_data /usr/share/nltk_data
script:  nosetests
